-- Create attendance_logs table
CREATE TABLE IF NOT EXISTS `attendance_logs` (
  `log_id` int(11) NOT NULL AUTO_INCREMENT,
  `attendance_id` int(11) DEFAULT NULL,
  `student_id` varchar(50) NOT NULL,
  `student_name` varchar(100) NOT NULL,
  `student_id_number` varchar(20) DEFAULT NULL,
  `section_id` int(11) DEFAULT NULL,
  `section_name` varchar(100) NOT NULL,
  `program` varchar(100) DEFAULT NULL,
  `subject_id` int(11) DEFAULT NULL,
  `subject_name` varchar(100) NOT NULL,
  `subject_code` varchar(20) DEFAULT NULL,
  `teacher_id` varchar(50) DEFAULT NULL,
  `teacher_name` varchar(100) NOT NULL,
  `date` date NOT NULL,
  `time_in` time DEFAULT NULL,
  `time_out` time DEFAULT NULL,
  `attendance_status` enum('present','late','absent','excused') NOT NULL,
  `excuse_status` enum('N/A','pending','approved','rejected') DEFAULT 'N/A',
  `late_minutes` int(11) DEFAULT NULL,
  `notes` text DEFAULT NULL,
  `remarks` text DEFAULT NULL,
  `recorded_by` varchar(50) NOT NULL,
  `recorded_by_name` varchar(100) NOT NULL,
  `ip_address` varchar(45) DEFAULT NULL,
  `device_info` text DEFAULT NULL,
  `created_at` timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `updated_at` timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  PRIMARY KEY (`log_id`),
  KEY `idx_student_id` (`student_id`),
  KEY `idx_section_id` (`section_id`),
  KEY `idx_subject_id` (`subject_id`),
  KEY `idx_teacher_id` (`teacher_id`),
  KEY `idx_date` (`date`),
  KEY `idx_attendance_status` (`attendance_status`),
  KEY `idx_program` (`program`),
  KEY `idx_created_at` (`created_at`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci; 